// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvpmuactwzwncyanqbyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2cG11YWN0d3p3bmN5YW5xYnliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4MTYyMTYsImV4cCI6MjA1NTM5MjIxNn0.LHV-PHN90YBhkANXCu6QulGqgJcygAoSjHlU28MIZQU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);